export interface TermsSection {
  id: string;
  number: number;
  title: string;
  iconName: string;
  summary: string;
  points: string[];
  importantNotice?: string;
}

export interface PrivacyPolicyData {
  title: string;
  lastUpdated: string;
  teamName: string;
  appName: string;
  intro: string;
  sections: TermsSection[];
  dataRights: {
    title: string;
    points: { title: string; desc: string }[];
  };
  contactInfo: {
    team: string;
    email: string;
    phone: string;
    address: string;
  };
}

export const TERMS_AND_PRIVACY_CONTENT: Record<string, PrivacyPolicyData> = {
  en: {
    title: 'KISAN SYNC – TERMS OF SERVICE & PRIVACY POLICY',
    lastUpdated: '30 August 2026',
    teamName: 'Team Hexa Knights',
    appName: 'Kisan Sync (SK.ai)',
    intro: 'Welcome to Kisan Sync (also called SK.ai), developed by Team Hexa Knights for the Smart India Hackathon. By downloading, accessing, or using the Kisan Sync mobile application or website ("App" or "Service"), you agree to these Terms of Service. If you do not agree, please do not use the App.',
    sections: [
      {
        id: 'about',
        number: 1,
        title: 'About Kisan Sync',
        iconName: 'Sprout',
        summary: 'Kisan Sync is an agricultural support platform designed to help Indian farmers make better decisions and receive fair produce prices.',
        points: [
          'AI-based crop disease and pest diagnosis using leaf, plant, and fruit photos.',
          'AI-based soil type analysis and crop recommendations using soil surface and dug soil photos.',
          'Multilingual guidance and voice assistance in 22+ Scheduled Indian languages.',
          'Farmer-to-buyer direct digital auction & escrow-ready marketplace.'
        ]
      },
      {
        id: 'eligibility',
        number: 2,
        title: 'Eligibility',
        iconName: 'UserCheck',
        summary: 'Criteria and prerequisites for using the Kisan Sync agricultural platform.',
        points: [
          'You must be at least 18 years old to use this App.',
          'By using the App, you confirm that you are a farmer, agri-entrepreneur, verified buyer, or actively involved in agriculture and that the information you provide is true.'
        ]
      },
      {
        id: 'account',
        number: 3,
        title: 'Your Account & Security',
        iconName: 'KeyRound',
        summary: 'Account credentials and user security obligations.',
        points: [
          'You may use core diagnostic features without creating an account.',
          'For auctions, credit ledger, history, or saving reports, you may create an account using your mobile number and farmer credentials.',
          'You are responsible for keeping your login credentials safe.',
          'You agree to provide accurate, up-to-date information.'
        ]
      },
      {
        id: 'acceptable-use',
        number: 4,
        title: 'Acceptable Use Guidelines',
        iconName: 'ShieldCheck',
        summary: 'Rules for respectful and lawful platform usage.',
        points: [
          'Use the App only for lawful agricultural purposes.',
          'Upload only real, unedited photos of your own crops or soil.',
          'Do not upload fake, misleading, offensive, or someone else’s photos.',
          'Do not use the App for any illegal activity or unauthorized commercial scraping.',
          'Do not attempt to harm, reverse-engineer, hack, or misuse the App.',
          'Be respectful while communicating with other users (especially in auction bidding).'
        ],
        importantNotice: 'We may suspend or permanently block accounts that violate these rules.'
      },
      {
        id: 'ai-disclaimer',
        number: 5,
        title: 'AI Diagnosis & Recommendations – Important Disclaimer',
        iconName: 'AlertTriangle',
        summary: 'Essential scientific boundaries of AI agricultural diagnostics.',
        points: [
          'Disease diagnosis, pest identification, soil analysis, and crop suggestions are generated by Artificial Intelligence (powered by Google Gemini and SK.ai models).',
          'These results are based strictly on visual cues from photos and information you provide.',
          'AI advice is not 100% accurate and is NEVER a substitute for advice from an Agriculture Officer, Krishi Vigyan Kendra (KVK), authorized Soil Testing Laboratory, or qualified agronomist.',
          'Always verify critical spray, fertilizer, or crop-changing decisions with local agricultural officers before executing.',
          'Team Hexa Knights and Kisan Sync are not liable for any loss of crop, money, or collateral damage resulting from reliance on AI suggestions.'
        ],
        importantNotice: 'Scientific Disclaimer: In case of acute crop blight or unknown pests, immediately visit your nearest Krishi Vigyan Kendra (KVK).'
      },
      {
        id: 'user-photos',
        number: 6,
        title: 'Photos & Content You Upload',
        iconName: 'Camera',
        summary: 'Ownership and strict privacy safeguards for your uploaded media.',
        points: [
          'You retain 100% full ownership of the photos and content you upload.',
          'By uploading, you grant Kisan Sync permission to process photos solely for providing diagnostics, recommendations, and platform improvements.',
          'We DO NOT sell, rent, or trade your photos or personal agricultural data to third-party advertisers.',
          'You can request permanent deletion of your photos and diagnostic history at any time.'
        ]
      },
      {
        id: 'marketplace-rules',
        number: 7,
        title: 'Auction & Marketplace Rules',
        iconName: 'ShoppingBag',
        summary: 'Operating standards for direct farmer-to-buyer transactions.',
        points: [
          'Farmers must upload honest photos, accurate quantities (in Quintals), and authentic quality grades of produce.',
          'Buyers must communicate respectfully and honor bid contracts in good faith.',
          'Kisan Sync operates as a direct facilitator connecting farmers and buyers; we are not a direct party to the bilateral sale.',
          'Both parties must verify produce quality, logistics, and payments prior to finalizing deals.',
          'Fake listings, price manipulation, artificial bidding, or abusive conduct lead to immediate permanent ban.'
        ]
      },
      {
        id: 'privacy-policy',
        number: 8,
        title: 'Privacy & Data Protection',
        iconName: 'Lock',
        summary: 'How personal information, farm locations, and records are safeguarded.',
        points: [
          'Your personal data is encrypted and handled in strict accordance with the Digital Personal Data Protection standards.',
          'Location data is accessed only with explicit permission to deliver hyperlocal weather forecasts and local Mandi MSP rates.',
          'Diagnostic scans and trade history remain private to your device/account unless you choose to list a crop publicly.'
        ]
      },
      {
        id: 'intellectual-property',
        number: 9,
        title: 'Intellectual Property',
        iconName: 'Award',
        summary: 'Proprietary assets and platform rights.',
        points: [
          'The App design, user interface, brand assets, logos, and names "Kisan Sync", "SK.ai", and "Hexa Knights" belong exclusively to Team Hexa Knights.',
          'You may not copy, reverse-engineer, modify, or distribute any part of the App codebase without explicit written consent.'
        ]
      },
      {
        id: 'liability',
        number: 10,
        title: 'Limitation of Liability',
        iconName: 'Scale',
        summary: 'Legal limits of liability under Indian jurisprudence.',
        points: [
          'To the maximum extent permitted by Indian law, Kisan Sync and Team Hexa Knights are not liable for direct, indirect, incidental, or consequential damages arising from app usage or reliance on AI outputs.',
          'We do not guarantee uninterrupted, error-free, or 100% continuous uptime.'
        ]
      },
      {
        id: 'updates',
        number: 11,
        title: 'Changes to These Terms',
        iconName: 'RefreshCw',
        summary: 'Periodic updates and farmer notification.',
        points: [
          'We may update these Terms from time to time to accommodate new features or regulatory requirements.',
          'Significant updates will be highlighted via in-app banners.',
          'Continued use of the App constitutes acceptance of revised terms.'
        ]
      },
      {
        id: 'termination',
        number: 12,
        title: 'Termination & Data Deletion',
        iconName: 'UserX',
        summary: 'Account closure and right to be forgotten.',
        points: [
          'We may suspend access if a user violates these Terms.',
          'You may stop using the App and request immediate deletion of your account and saved diagnostic records at any time.'
        ]
      },
      {
        id: 'governing-law',
        number: 13,
        title: 'Governing Law & Jurisdiction',
        iconName: 'Gavel',
        summary: 'Applicable legal framework.',
        points: [
          'These Terms are governed by and construed in accordance with the Laws of India.',
          'Any disputes shall be subject to the exclusive jurisdiction of the competent courts in India.'
        ]
      },
      {
        id: 'contact',
        number: 14,
        title: 'Contact & Grievance Redressal',
        iconName: 'Mail',
        summary: 'Official channels for support, privacy queries, and assistance.',
        points: [
          'Team: Team Hexa Knights (Smart India Hackathon Project)',
          'Email: support@kisansync.in / hexaknights.sih@gmail.com',
          'Toll-Free Helpline: 1800-KISAN-SYNC (1800-547-267)',
          'Pan-India Support: Available in 22+ Scheduled Indian Languages.'
        ]
      }
    ],
    dataRights: {
      title: 'Your Farmer Data Rights',
      points: [
        { title: 'Right to Access', desc: 'You can inspect all past AI scans, trade ledgers, and credit profile records anytime.' },
        { title: 'Right to Rectify', desc: 'You can modify or update listing parameters and personal contact details.' },
        { title: 'Right to Erasure', desc: 'Submit a 1-click request to permanently delete all uploaded photos and diagnostic history.' },
        { title: 'Zero Data Commercialization', desc: 'Your crop images and farm data are never sold to advertisers or third-party brokers.' }
      ]
    },
    contactInfo: {
      team: 'Team Hexa Knights',
      email: 'support@kisansync.in',
      phone: '1800-KISAN-SYNC (547-267)',
      address: 'Smart India Hackathon (SIH) Innovation Cell, Ministry of Education, Government of India'
    }
  },

  gu: {
    title: 'કિસાન સિંક – સેવાની શરતો અને ગોપનીયતા નીતિ (Terms of Service)',
    lastUpdated: '30 ઓગસ્ટ 2026',
    teamName: 'ટીમ હેક્ઝા નાઈટ્સ (Team Hexa Knights)',
    appName: 'કિસાન સિંક / SK.ai',
    intro: 'કિસાન સિંક (SK.ai) માં આપનું હાર્દિક સ્વાગત છે, જે સ્માર્ટ ઇન્ડિયા હેકાથોન (SIH) માટે ટીમ હેક્ઝા નાઈટ્સ દ્વારા વિકસાવવામાં આવ્યું છે. આ એપનો ઉપયોગ કરીને તમે નીચે મુજબની સેવાની શરતો અને ગોપનીયતા નીતિઓ સાથે સંમત થાઓ છો.',
    sections: [
      {
        id: 'about',
        number: 1,
        title: '૧. કિસાન સિંક વિશે',
        iconName: 'Sprout',
        summary: 'કિસાન સિંક ભારતીય ખેડૂત ભાઈઓને યોગ્ય નિર્ણયો લેવા અને પાકના પોષણક્ષમ ભાવ મેળવવા માટે તૈયાર કરેલ ડિજિટલ પ્લેટફોર્મ છે.',
        points: [
          'છોડ, પાન અને ફળના ફોટો દ્વારા એઆઈ (AI) આધારિત પાક રોગ અને જીવાત નિદાન.',
          'જમીનના ફોટો દ્વારા જમીનનો પ્રકાર ઓળખ અને શ્રેષ્ઠ પાકની ભલામણ.',
          'ગુજરાતી સહિત ૨૨+ માન્ય ભારતીય ભાષાઓમાં વોઇસ અને ટેક્સ્ટ માર્ગદર્શન.',
          'ખેડૂતથી સીધા વેપારી વચ્ચે પારદર્શક ઓનલાઇન હરાજી અને બજાર ભાવ.'
        ]
      },
      {
        id: 'eligibility',
        number: 2,
        title: '૨. પાત્રતા (Eligibility)',
        iconName: 'UserCheck',
        summary: 'એપના ઉપયોગ માટેના નિયમો.',
        points: [
          'આ એપનો ઉપયોગ કરવા માટે તમારી ઉંમર ૧૮ વર્ષ કે તેથી વધુ હોવી જોઈએ.',
          'તમે પુષ્ટિ કરો છો કે તમે ખેડૂત, કૃષિ ઉદ્યોગસાહસિક અથવા કૃષિ ક્ષેત્ર સાથે સંકળાયેલ છો અને સાચી માહિતી આપો છો.'
        ]
      },
      {
        id: 'account',
        number: 3,
        title: '૩. તમારું એકાઉન્ટ અને સુરક્ષા',
        iconName: 'KeyRound',
        summary: 'એકાઉન્ટ વિગતો અને સાવચેતી.',
        points: [
          'રોગ નિદાન જેવા મૂળભૂત ફીચર્સ માટે એકાઉન્ટ વગર પણ ઉપયોગ કરી શકાય છે.',
          'હરાજી અને પાક વેચાણ માટે મોબાઈલ નંબર દ્વારા નોંધણી જરૂરી છે.',
          'તમારા લોગિન વિગતો સુરક્ષિત રાખવાની જવાબદારી તમારી છે.'
        ]
      },
      {
        id: 'acceptable-use',
        number: 4,
        title: '૪. ઉપયોગના નિયમો (Acceptable Use)',
        iconName: 'ShieldCheck',
        summary: 'પ્લેટફોર્મના યોગ્ય ઉપયોગ અંગેની માર્ગદર્શિકા.',
        points: [
          'એપનો ઉપયોગ માત્ર કાયદેસર ખેતીવાડી સંબંધિત હેતુઓ માટે જ કરવો.',
          'માત્ર તમારા પોતાના ખેતરના સાચા અને અસલી ફોટો જ અપલોડ કરવા.',
          'ખોટા, ભ્રામક અથવા બીજાના ફોટા અપલોડ કરવા નહીં.',
          'અન્ય ખેડૂતો કે વેપારીઓ સાથે સન્માનપૂર્વક વાતચીત કરવી.'
        ],
        importantNotice: 'નિયમોનો ભંગ કરનાર એકાઉન્ટને તાત્કાલિક સ્થગિત અથવા બ્લોક કરવામાં આવી શકે છે.'
      },
      {
        id: 'ai-disclaimer',
        number: 5,
        title: '૫. એઆઈ (AI) નિદાન અને સલાહ – મહત્વપૂર્ણ ડિસ્ક્લેમર',
        iconName: 'AlertTriangle',
        summary: 'એઆઈ આધારિત પરિણામોની વૈજ્ઞાનિક મર્યાદાઓ.',
        points: [
          'રોગ નિદાન, જીવાત ઓળખ અને જમીનની ભલામણો કૃત્રિમ બુદ્ધિમત્તા (Google Gemini / SK.ai) દ્વારા જનરેટ થાય છે.',
          'આ પરિણામો માત્ર તમે આપેલા ફોટાના વિઝ્યુઅલ લક્ષણો પર આધારિત છે.',
          'એઆઈ સલાહ ૧૦૦% સચોટ હોતી નથી અને તે કૃષિ અધિકારી, કૃષિ વિજ્ઞાન કેન્દ્ર (KVK) અથવા પ્રયોગશાળાના વૈજ્ઞાનિક પરીક્ષણનો વિકલ્પ નથી.',
          'મોટા નિર્ણયો લેતા પહેલાં સ્થાનિક કૃષિ નિષ્ણાત અથવા KVK ની સલાહ અવશ્ય લેવી.',
          'ટીમ હેક્ઝા નાઈટ્સ અને કિસાન સિંક કોઈપણ આર્થિક કે પાક નુકસાન માટે જવાબદાર રહેશે નહીં.'
        ],
        importantNotice: 'નોંધ: પાકમાં ગંભીર રોગચાળો હોય ત્યારે નજીકના કૃષિ વિજ્ઞાન કેન્દ્ર (KVK) નો તાત્કાલિક સંપર્ક કરો.'
      },
      {
        id: 'user-photos',
        number: 6,
        title: '૬. તમારા દ્વારા અપલોડ કરાયેલા ફોટા અને ડેટા',
        iconName: 'Camera',
        summary: 'ડેટાની માલિકી અને સુરક્ષા.',
        points: [
          'તમે અપલોડ કરેલા ફોટાની સંપૂર્ણ માલિકી તમારી પોતાની રહે છે.',
          'અમે તમારા ફોટા કે અંગત વિગતો કોઈપણ જાહેરાત કંપની કે ત્રીજા પક્ષને વેચતા નથી.',
          'તમે કોઈપણ સમયે તમારા સ્કેન ઇતિહાસ અને ફોટા ડિલીટ કરવાની વિનંતી કરી શકો છો.'
        ]
      },
      {
        id: 'marketplace-rules',
        number: 7,
        title: '૭. હરાજી અને માર્કેટપ્લેસ નિયમો',
        iconName: 'ShoppingBag',
        summary: 'સીધા વેચાણ માટેની માર્ગદર્શિકા.',
        points: [
          'ખેડૂતોએ પાકનો સાચો જથ્થો (ક્વિન્ટલમાં) અને સાચો ગુણવત્તા ગ્રેડ દર્શાવવો.',
          'કિસાન સિંક માત્ર ખેડૂત અને વેપારીને જોડતું માધ્યમ છે; વાસ્તવિક સોદામાં બંને પક્ષોએ ખરાઈ કરવી જરૂરી છે.',
          'ખોટા લિસ્ટિંગ કે છેતરપિંડી બદલ કાયમી પ્રતિબંધ મૂકવામાં આવશે.'
        ]
      },
      {
        id: 'privacy-policy',
        number: 8,
        title: '૮. પ્રાઇવસી પોલિસી અને ડેટા સુરક્ષા',
        iconName: 'Lock',
        summary: 'ડેટા સુરક્ષા વ્યવસ્થા.',
        points: [
          'ખેડૂતનો અંગત ડેટા અને લોકેશન ફક્ત સ્થાનિક હવામાન અને માર્કેટ યાર્ડના ભાવ આપવા માટે જ વપરાય છે.',
          'તમામ ડેટા સુરક્ષિત રીતે એન્ક્રિપ્ટ રાખવામાં આવે છે.'
        ]
      },
      {
        id: 'intellectual-property',
        number: 9,
        title: '૯. બૌદ્ધિક સંપત્તિ (Intellectual Property)',
        iconName: 'Award',
        summary: 'કોપીરાઈટ અને ટ્રેડમાર્ક.',
        points: [
          'કિસાન સિંક, SK.ai અને ટીમ હેક્ઝા નાઈટ્સના તમામ કોપીરાઈટ અને ટ્રેડમાર્ક સુરક્ષિત છે.',
          'કોઈપણ ભાગની અનધિકૃત નકલ કરવી કાયદાકીય ગુનો છે.'
        ]
      },
      {
        id: 'liability',
        number: 10,
        title: '૧૦. જવાબદારીની મર્યાદા (Limitation of Liability)',
        iconName: 'Scale',
        summary: 'ભારતીય કાયદા હેઠળ જવાબદારી.',
        points: [
          'ભારતીય કાયદા અનુસાર, કોઈપણ પરોક્ષ નુકસાન કે પાક ક્ષતિ માટે પ્લેટફોર્મ જવાબદાર રહેશે નહીં.'
        ]
      },
      {
        id: 'updates',
        number: 11,
        title: '૧૧. શરતોમાં ફેરફાર',
        iconName: 'RefreshCw',
        summary: 'સમયાનુસાર સુધારા.',
        points: [
          'જરૂર પડ્યે નિયમોમાં સુધારો કરવામાં આવશે અને એપમાં તેની સૂચના આપવામાં આવશે.'
        ]
      },
      {
        id: 'termination',
        number: 12,
        title: '૧૨. એકાઉન્ટ સમાપ્તિ અને ડેટા હટાવવો',
        iconName: 'UserX',
        summary: 'ડેટા ડિલીટ કરવાનો અધિકાર.',
        points: [
          'ખેડૂત કોઈપણ સમયે પોતાનો ડેટા કાયમી ધોરણે દૂર કરવાની વિનંતી કરી શકે છે.'
        ]
      },
      {
        id: 'governing-law',
        number: 13,
        title: '૧૩. કાયદાકીય અધિકારક્ષેત્ર',
        iconName: 'Gavel',
        summary: 'ભારતીય કાયદા લાગુ થશે.',
        points: [
          'આ સેવાની શરતો ભારતના પ્રવર્તમાન કાયદાઓ હેઠળ માન્ય રહેશે.'
        ]
      },
      {
        id: 'contact',
        number: 14,
        title: '૧૪. સંપર્ક અને સહાયતા',
        iconName: 'Mail',
        summary: 'સત્તાવાર સહાય ચેનલો.',
        points: [
          'ટીમ: ટીમ હેક્ઝા નાઈટ્સ (Smart India Hackathon)',
          'ઈમેઈલ: support@kisansync.in',
          'ટોલ-ફ્રી હેલ્પલાઈન: 1800-KISAN-SYNC (1800-547-267)',
          'ભાષાઓ: ૨૨+ ભારતીય પ્રાદેશિક ભાષાઓમાં ઉપલબ્ધ.'
        ]
      }
    ],
    dataRights: {
      title: 'તમારા ડેટા અધિકારો',
      points: [
        { title: 'ડેટા જોવાનો અધિકાર', desc: 'તમે કરેલા તમામ જૂના સ્કેન અને વેપાર ખાતાવહી ગમે ત્યારે જોઈ શકો છો.' },
        { title: 'સુધારવાનો અધિકાર', desc: 'તમારી પાક લિસ્ટિંગ અને પ્રોફાઈલ વિગતો સુધારી શકો છો.' },
        { title: 'ડેટા ડિલીટ કરવાનો અધિકાર', desc: 'એક ક્લિકમાં તમારા તમામ ફોટા અને સ્કેન રેકોર્ડ્સ કાયમી કાઢી શકો છો.' },
        { title: 'કોઈ ડેટા વેચાણ નહીં', desc: 'તમારી વિગતો ક્યારેય ત્રીજા પક્ષ કે જાહેરાતકારોને વેચવામાં આવતી નથી.' }
      ]
    },
    contactInfo: {
      team: 'ટીમ હેક્ઝા નાઈટ્સ (Team Hexa Knights)',
      email: 'support@kisansync.in',
      phone: '1800-KISAN-SYNC (547-267)',
      address: 'Smart India Hackathon, Ministry of Education, Government of India'
    }
  },

  hi: {
    title: 'किसान सिंक – सेवा की शर्तें और गोपनीयता नीति (Terms of Service)',
    lastUpdated: '30 अगस्त 2026',
    teamName: 'टीम हेक्सा नाइट्स (Team Hexa Knights)',
    appName: 'किसान सिंक / SK.ai',
    intro: 'किसान सिंक (SK.ai) में आपका स्वागत है, जिसे स्मार्ट इंडिया हैकथॉन (SIH) के लिए टीम हेक्सा नाइट्स द्वारा विकसित किया गया है। ऐप का उपयोग करके आप इन सेवा की शर्तों और गोपनीयता नीति से सहमत होते हैं।',
    sections: [
      {
        id: 'about',
        number: 1,
        title: '१. किसान सिंक के बारे में',
        iconName: 'Sprout',
        summary: 'भारतीय किसान भाइयों को सही कृषि निर्णय लेने और उपज का उचित मूल्य दिलाने हेतु डिजिटल मंच।',
        points: [
          'पत्ती/पौधे के फोटो द्वारा एआई (AI) आधारित फसल रोग एवं कीट पहचान।',
          'मिट्टी के फोटो द्वारा मिट्टी के प्रकार का विश्लेषण और सर्वश्रेष्ठ फसल सुझाव।',
          'हिंदी सहित 22+ भारतीय भाषाओं में बहुभाषी वॉयस एवं टेक्स्ट मार्गदर्शन।',
          'किसान से सीधे खरीदार तक पारदर्शी ई-मंडी और नीलामी।'
        ]
      },
      {
        id: 'eligibility',
        number: 2,
        title: '२. पात्रता (Eligibility)',
        iconName: 'UserCheck',
        summary: 'उपयोग की शर्तें।',
        points: [
          'इस ऐप का उपयोग करने के लिए आपकी आयु 18 वर्ष या उससे अधिक होनी चाहिए।',
          'आप पुष्टि करते हैं कि आप किसान या कृषि से जुड़े व्यक्ति हैं और सही जानकारी प्रदान करते हैं।'
        ]
      },
      {
        id: 'account',
        number: 3,
        title: '३. आपका खाता और सुरक्षा',
        iconName: 'KeyRound',
        summary: 'खाता सुरक्षा जिम्मेदारियां।',
        points: [
          'रोग पहचान जैसी बुनियादी सुविधाएं बिना खाते के भी उपलब्ध हैं।',
          'नीलामी और फसल बिक्री के लिए मोबाइल नंबर द्वारा पंजीकरण आवश्यक है।',
          'अपने लॉगिन विवरण को सुरक्षित रखने की जिम्मेदारी आपकी है।'
        ]
      },
      {
        id: 'acceptable-use',
        number: 4,
        title: '४. स्वीकार्य उपयोग नियम',
        iconName: 'ShieldCheck',
        summary: 'सद्भावनापूर्ण उपयोग की शर्तें।',
        points: [
          'ऐप का उपयोग केवल वैध कृषि कार्यों के लिए करें।',
          'केवल अपनी वास्तविक फसल या मिट्टी के फोटो अपलोड करें।',
          'फर्जी, भ्रामक या किसी अन्य व्यक्ति के फोटो अपलोड न करें।',
          'अन्य किसानों और खरीदारों के साथ सम्मानपूर्वक संवाद करें।'
        ],
        importantNotice: 'नियमों का उल्लंघन करने वाले खातों को स्थायी रूप से ब्लॉक किया जा सकता है।'
      },
      {
        id: 'ai-disclaimer',
        number: 5,
        title: '५. एआई (AI) निदान और सलाह – महत्वपूर्ण अस्वीकरण',
        iconName: 'AlertTriangle',
        summary: 'एआई की वैज्ञानिक सीमाएं।',
        points: [
          'रोग निदान और मिट्टी की सलाह आर्टिफिशियल इंटेलिजेंस (Google Gemini / SK.ai) द्वारा दी जाती है।',
          'यह सलाह केवल आपके द्वारा दिए गए फोटो के दृश्य संकेतों पर आधारित है।',
          'एआई सलाह 100% सटीक नहीं होती और यह कृषि विज्ञान केंद्र (KVK), कृषि अधिकारी या प्रयोगशाला परीक्षण का विकल्प नहीं है।',
          'किसी भी बड़े छिड़काव या फसल परिवर्तन से पहले स्थानीय कृषि विशेषज्ञों से परामर्श अवश्य लें।',
          'टीम हेक्सा नाइट्स और किसान सिंक किसी भी फसल या आर्थिक नुकसान के लिए उत्तरदायी नहीं होंगे।'
        ],
        importantNotice: 'वैज्ञानिक चेतावनी: गंभीर रोग की स्थिति में तुरंत नजदीकी कृषि विज्ञान केंद्र (KVK) से संपर्क करें।'
      },
      {
        id: 'user-photos',
        number: 6,
        title: '६. आपके द्वारा अपलोड किए गए फोटो और डेटा',
        iconName: 'Camera',
        summary: 'डेटा गोपनीयता और स्वामित्व।',
        points: [
          'आपके द्वारा अपलोड किए गए फोटो पर आपका पूरा स्वामित्व रहता है।',
          'हम आपके फोटो या व्यक्तिगत डेटा को किसी विज्ञापनदाता या तीसरे पक्ष को कभी नहीं बेचते।',
          'आप कभी भी अपने फोटो और इतिहास को हटाने का अनुरोध कर सकते हैं।'
        ]
      },
      {
        id: 'marketplace-rules',
        number: 7,
        title: '७. मंडी और नीलामी के नियम',
        iconName: 'ShoppingBag',
        summary: 'सीधी बिक्री के नियम।',
        points: [
          'किसान अपनी उपज की सही मात्रा (क्विंटल में) और सही ग्रेड दर्ज करें।',
          'किसान सिंक केवल मंच प्रदान करता है, वास्तविक सौदे की पुष्टि दोनों पक्षों को स्वयं करनी होगी।',
          'फर्जी लिस्टिंग करने पर खाता तुरंत बंद कर दिया जाएगा।'
        ]
      },
      {
        id: 'privacy-policy',
        number: 8,
        title: '८. गोपनीयता और डेटा सुरक्षा',
        iconName: 'Lock',
        summary: 'डेटा सुरक्षा।',
        points: [
          'लोकेशन का उपयोग केवल स्थानीय मौसम और नजदीकी मंडी भाव दिखाने के लिए किया जाता है।',
          'आपका डेटा आधुनिक मानकों के अनुसार सुरक्षित और एन्क्रिप्टेड है।'
        ]
      },
      {
        id: 'intellectual-property',
        number: 9,
        title: '९. बौद्धिक संपदा',
        iconName: 'Award',
        summary: 'स्वामित्व अधिकार।',
        points: [
          'किसान सिंक, SK.ai और टीम हेक्सा नाइट्स के सभी अधिकार सुरक्षित हैं।'
        ]
      },
      {
        id: 'liability',
        number: 10,
        title: '१०. दायित्व की सीमा',
        iconName: 'Scale',
        summary: 'कानूनी सीमाएं।',
        points: [
          'भारतीय कानून के तहत अनुमत सीमा तक, किसी भी नुकसान के लिए ऐप उत्तरदायी नहीं होगा।'
        ]
      },
      {
        id: 'updates',
        number: 11,
        title: '११. शर्तों में संशोधन',
        iconName: 'RefreshCw',
        summary: 'नियमों में बदलाव।',
        points: [
          'शर्तों में बदलाव होने पर ऐप में सूचित किया जाएगा।'
        ]
      },
      {
        id: 'termination',
        number: 12,
        title: '१२. खाता समाप्ति और डेटा निष्कासन',
        iconName: 'UserX',
        summary: 'डेटा डिलीट करने की सुविधा।',
        points: [
          'आप किसी भी समय अपना खाता और डेटा हटाने का अनुरोध कर सकते हैं।'
        ]
      },
      {
        id: 'governing-law',
        number: 13,
        title: '१३. लागू कानून',
        iconName: 'Gavel',
        summary: 'भारतीय न्यायपालिका।',
        points: [
          'ये शर्तें भारत के कानूनों द्वारा शासित होंगी।'
        ]
      },
      {
        id: 'contact',
        number: 14,
        title: '१४. संपर्क और सहायता',
        iconName: 'Mail',
        summary: 'हेल्पलाइन और संपर्क।',
        points: [
          'टीम: टीम हेक्सा नाइट्स (Smart India Hackathon)',
          'ईमेल: support@kisansync.in',
          'टोल-फ्री हेल्पलाइन: 1800-KISAN-SYNC (1800-547-267)',
          'उपलब्धता: 22+ भारतीय भाषाओं में उपलब्ध।'
        ]
      }
    ],
    dataRights: {
      title: 'आपके डेटा अधिकार',
      points: [
        { title: 'डेटा देखने का अधिकार', desc: 'आप अपने पुराने स्कैन और बहीखाते कभी भी देख सकते हैं।' },
        { title: 'सुधार का अधिकार', desc: 'अपनी फसल लिस्टिंग और प्रोफाइल जानकारी बदल सकते हैं।' },
        { title: 'डेटा हटाने का अधिकार', desc: 'एक क्लिक में अपनी फोटो और रिकॉर्ड्स हमेशा के लिए डिलीट कर सकते हैं।' },
        { title: 'डेटा की कोई बिक्री नहीं', desc: 'आपकी जानकारी किसी भी तीसरे पक्ष को कभी नहीं बेची जाती।' }
      ]
    },
    contactInfo: {
      team: 'टीम हेक्सा नाइट्स (Team Hexa Knights)',
      email: 'support@kisansync.in',
      phone: '1800-KISAN-SYNC (547-267)',
      address: 'Smart India Hackathon, Ministry of Education, Government of India'
    }
  }
};

export const getTermsTranslation = (langCode: string): PrivacyPolicyData => {
  return TERMS_AND_PRIVACY_CONTENT[langCode] || TERMS_AND_PRIVACY_CONTENT.en;
};
